<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'username' => 'admin',
                'password' => Hash::make('admin'),
                'firstname' => 'Jeremae',
                'middlename' => 'G',
                'lastname' => 'Payot',
                'status' => 'active',
                // 'branch_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'adminn',
                'password' => Hash::make('admin'),
                'firstname' => 'Janine',
                'middlename' => 'L',
                'lastname' => 'Descalar',
                'status' => 'active',
                // 'branch_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'adminnn',
                'password' => Hash::make('admin'),
                'firstname' => 'Mark',
                'middlename' => '',
                'lastname' => '',
                'status' => 'active',
                // 'branch_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);

        DB::table('user_accessibility')->insert([
            [
                'id' => '1',
                'access_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '4',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '5',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '6',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '7',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '8',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '9',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '10',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '11',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '12',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '13',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '14',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '15',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '16',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '17',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '18',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '19',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '20',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '21',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '22',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '23',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '24',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '25',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '26',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '27',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '28',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '29',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '30',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '31',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '32',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '33',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '34',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '35',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '36',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '37',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '38',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '39',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '40',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '41',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '42',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '43',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '44',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '45',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '46',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '47',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '48',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '49',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '50',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '51',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '52',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => '1',
                'access_id' => '53',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        DB::table('branch')->insert([
            [
                'branch_code' => "001",
                'branch_name' => "Butuan City",
                'branch_manager' => "Janine L. Descallar",
                'branch_address' => "Butuan City",
                'status' => "active",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'branch_code' => "002",
                'branch_name' => "Nasipit",
                'branch_manager' => "Jomel T. Gallanero",
                'branch_address' => "Nasipit",
                'status' => "active",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'branch_code' => "003",
                'branch_name' => "Gingoog",
                'branch_manager' => "Mark",
                'branch_address' => "Gingoog City",
                'status' => "active",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);

        DB::table('account_officer')->insert([
            [
                'ao_id' => '1',
                'name' => 'Robert Dumaog',
                'branch_id' => '001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'ao_id' => '2',
                'name' => 'Jimmy A. Castillo',
                'branch_id' => '001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '3',
                'name' => 'Jomel T. Gallenero',
                'branch_id' => '001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '4',
                'name' => 'Randy F. Navarro',
                'branch_id' => '001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '5',
                'name' => 'Butuan Branch Office',
                'branch_id' => '001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '21',
                'name' => 'John Rey Mark Jamen',
                'branch_id' => '002',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '22',
                'name' => 'John Mark Barcenas',
                'branch_id' => '002',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '23',
                'name' => 'Lemuel Roy S Salcedo',
                'branch_id' => '003',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '24',
                'name' => 'Nasipit Branch Ofs.',
                'branch_id' => '001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '25',
                'name' => 'Janine L. Descallar',
                'branch_id' => '002',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '40',
                'name' => 'Jomel T. Gallanero',
                'branch_id' => '002',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '41',
                'name' => 'Unknown AO',
                'branch_id' => '001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);

        DB::table('account_officer_branch')->insert([
            [
                'ao_id' => '1',
                'branch_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'ao_id' => '2',
                'branch_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '3',
                'branch_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '4',
                'branch_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '5',
                'branch_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '25',
                'branch_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '3',
                'branch_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '21',
                'branch_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '22',
                'branch_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '23',
                'branch_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '24',
                'branch_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '25',
                'branch_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ao_id' => '40',
                'branch_id' => '3',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);

        DB::table('center')->insert([
            [
                'center' => 'Anthorium Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Asparagus Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Babies Breath Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Banda Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Birds of Paradise',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Bromillad Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Centenial Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Crisantium Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Dahlia Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Dancing Lady Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Gumamela Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Holand Rose Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Jasmine Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Lady Kenedy Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Orchids Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Queen of the Night',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Red Bull Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Rosal Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Rosas Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Rose Peligoson Cntr',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Sampaguita Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'San Francisco Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Santan Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Sunflower Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Sweet Lanta-aw Cntr',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Verbina Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Waling-Waling Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Paradise',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Papaya Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Lansones Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Daisy Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Apple Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Mango Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Jack Fruit Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Strawberry Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Orange Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Durian Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Rambutan Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Banana Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Star Apple Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Lawaan Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Almond Tree Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Daffodil Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Narra Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Pomelo Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Cherry Blossom Cntr',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Gemelina Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Hyacinth Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Mangostene Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Grapes Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Tulips Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Calla Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Tugas Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Camelia Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Ipil-Ipil Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Carnation Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Talisay Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Cherry Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Pineapple Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Lavender Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Lily Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Pink Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Millions Flower Cntr',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Pine Tree Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Bellflower Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Mahogany Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Apitong Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Acacia Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Mangroove Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Cypress Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Blackberry Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Raspberry Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Marigold Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'IRIS Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Bluebell Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Pear Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Euphobia Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Clover Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Buttercup Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Palm Tree Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Guava Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Oak Tree Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Lotus Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Mirasol Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Guyabano Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Cactus Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Birch Tree Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Garlands Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Caphor Tree Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Magnoloa Tree Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Blueberry Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Canistel Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Pigeon Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Sparrow Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Miracle Fruit Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Watermelon Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Bluebird Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Humming Bird Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Pecan Tree Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Honey Dew Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Eucalyptus Tree Cntr',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Basswood Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Dove Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Passion Fruit Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Mangium Tree Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Parrot Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Woodpecker Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Rubber Tree Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Aspen Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Pin Cherry Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Maple Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Plover Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Eagle Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Apricot Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Lychee Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Lychee I Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Lychee II Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Lychee III Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Lychee IV Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Grapes I Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Cashew Fruit I Cntr',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Falcon 1 Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Falcon 2 Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Falcon 3 Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Tangerine Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Cranberry Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Quince Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Cashew II Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Loverbird 1 Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Loverbird 2 Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Loverbird 3 Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Tailorbird 1 Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Tailorbird 2 Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Tailorbird 3 Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Redcedar I Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'Redcedar II Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'ROSE 1 Center',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'MORNING GLORY CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'BOUGAINVILLA CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'ALBATROSS CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'ALBATROSS II CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'FLAMINGO CENTER 1',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'FLAMINGO CENTER 2',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'TAMARIND CENTER I',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'TAMARIND CENTER II',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'BASSWOOD-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'BIRCH-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'CAMPHOR-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'EUCALYPTUS-PROBLEMAT',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'IPIL-IPIL- PROBLEMAT',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'LAWAAN-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'MAGNOLIA-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'MANGIUM-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'MANGROOVE-PROBLEMATI',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'NARRA-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'OAK TREE-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PINE TREE-PROBLEMATI',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'RUBBER-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'CANISTEL-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'CASHEW-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'CRANBERRY-PROBLEMATI',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'GRAPES-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'LYCHEE-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'MANGO-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'MANGOSTENE-PROBLEMAT',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'MIRACLE-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'ORANGE-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PASSION-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'POMELO-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'QUINCE-PROBLEMATIC',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'STAR APPLE-PROBLEMAT',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'WALNUT CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PLUM CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PINE TREE CENTER II',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'CHICO CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'NECTARINE CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'CANTALOUPE CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'TANGUILE CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'MOLAVE CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'WILLOW CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'FANTAIL CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'OSPREY CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'SWALLOW CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'POMEGRANATE CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PERSIMMON CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'REDCURRANT CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'MANDARINE CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'YUZU CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PLOVER 1 CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'NEEM TREE CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'CHERIMOYA CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'OLIVE CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'APRICOT PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'BANANA PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'CRANBERRY PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'DURIAN PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PLUM PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PAPAYA PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'ALMOND PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'APITONG PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'CAMPHOR PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'MAPLE PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PECAN PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'REDCEDAR PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PD ALBATROSS CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PD ALBATROSSII CENTE',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PD DOVE CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PD EAGLE CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PD FLAMINGO CENTER2',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PD FALCON 1 CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PD FALCON 2 CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PD FALCON 3 CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PD LOVEBIRD 1 CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PD LOVEBIRD 2 CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PD LOVEBIRD 3 CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PD PARROT CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PD PEGION CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PD SPARROW CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PD TAILORBIRD2 CENTE',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'POLYALTHIA CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'APRICOT II CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'NECTARINE PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'TANGUILE PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'TANGERINE PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'WATERMELON PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'PHYSALIS CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'JACK FRUIT PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'CHICO PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'STRAWBERRY PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'TAMARIND PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'BLUEBERRY PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'MOLAVE PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'CYPRESS PD CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'LONGAN CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'KIWI CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'BELLFLOWER 2',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'CANARY',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'TURMERIC TREE CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'CRANE CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'BUTTERCUP-2',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'RED TOP CENTER',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'center' => 'CHERRY BLOSSOM',
                'day_sched' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        DB::table('product')->insert([
            [
                'product_code' => '001',
                'product_name' => 'Micro Individual',
                'interest_rate' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_code' => '002',
                'product_name' => 'Micro Group',
                'interest_rate' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_code' => '003',
                'product_name' => 'Pension Loan',
                'interest_rate' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_code' => '004',
                'product_name' => 'Pnsion Emergency',
                'interest_rate' => '2',
                'status' => 'inactive',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_code' => '005',
                'product_name' => 'Salary Loan',
                'interest_rate' => '2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_code' => '006',
                'product_name' => 'Salry Emergency',
                'interest_rate' => '2',
                'status' => 'inactive',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_code' => '007',
                'product_name' => 'SME Loan',
                'interest_rate' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_code' => '008',
                'product_name' => 'Allotment Loan',
                'interest_rate' => '4',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_code' => '000',
                'product_name' => 'Unknown Product',
                'interest_rate' => '0',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);

        DB::table('user_branch')->insert([
            [
                'id' => "1",
                'branch_id' => "1",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => "2",
                'branch_id' => "2",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => "3",
                'branch_id' => "3",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
