name: Build and Push to CI-Pipeline Branch

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["staging", "main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  APPLICATION_NAME: "macloans"
  GIT_USERNAME: "engtech-projects"
  REPOSITORY_NAME: "MAC-loans"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.vars.outputs.short_ref }}
      - name: Build Laravel with Vue
        run: |
              composer install --no-dev -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
              npm ci
              npm run production
              rm -rf .git
              rm -rf .gitignore
              git config --global user.email "engtechsolutions2020@gmail.com"
              git config --global user.name "EngtechDeploy"
              git init
              git add -A
              git commit -m 'deploy to CI-Pipeline'
              git push -f https://$GIT_USERNAME:${{ secrets.GITHUB_TOKEN }}@github.com/$GIT_USERNAME/$REPOSITORY_NAME.git master:ci-pipe-${{ steps.vars.outputs.short_ref }}
        shell: bash

  build-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.vars.outputs.short_ref }}
      - name: Build Laravel
        run: |
              composer install --no-dev -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
              npm ci
              npm run production
              rm -rf .git
              rm -rf .gitignore
              git config --global user.email "engtechsolutions2020@gmail.com"
              git config --global user.name "EngtechDeploy"
              git init
              git add -A
              git commit -m 'deploy to CI-Pipeline'
              git push -f https://$GIT_USERNAME:${{ secrets.GITHUB_TOKEN }}@github.com/$GIT_USERNAME/$REPOSITORY_NAME.git master:ci-pipe-${{ steps.vars.outputs.short_ref }}
        shell: bash
